// <auto-generated />
using System;
using EcoFoodAPI.Data;
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Infrastructure;
using Microsoft.EntityFrameworkCore.Storage.ValueConversion;

#nullable disable

namespace EcoFoodAPI.Migrations
{
    [DbContext(typeof(EcoFoodDbContext))]
    partial class EcoFoodDbContextModelSnapshot : ModelSnapshot
    {
        protected override void BuildModel(ModelBuilder modelBuilder)
        {
#pragma warning disable 612, 618
            modelBuilder
                .HasAnnotation("ProductVersion", "8.0.0")
                .HasAnnotation("Relational:MaxIdentifierLength", 64);

            modelBuilder.Entity("EcoFoodAPI.Models.Categorie", b =>
                {
                    b.Property<int>("IdCategorie")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    b.Property<string>("NomCategorie")
                        .IsRequired()
                        .HasColumnType("longtext");

                    b.HasKey("IdCategorie");

                    b.ToTable("Categories");
                });

            modelBuilder.Entity("EcoFoodAPI.Models.Message", b =>
                {
                    b.Property<int>("IdMessage")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    b.Property<DateTime?>("DateEnvoi")
                        .HasColumnType("datetime(6)");

                    b.Property<int>("IdProduit")
                        .HasColumnType("int");

                    b.Property<int>("IdProduitNavigationIdProduit")
                        .HasColumnType("int");

                    b.Property<int>("IdReceiver")
                        .HasColumnType("int");

                    b.Property<int>("IdSender")
                        .HasColumnType("int");

                    b.Property<string>("Texte")
                        .IsRequired()
                        .HasColumnType("longtext");

                    b.HasKey("IdMessage");

                    b.HasIndex("IdProduitNavigationIdProduit");

                    b.HasIndex("IdReceiver");

                    b.HasIndex("IdSender");

                    b.ToTable("Messages");
                });

            modelBuilder.Entity("EcoFoodAPI.Models.Produit", b =>
                {
                    b.Property<int>("IdProduit")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    b.Property<DateOnly?>("DateExpiration")
                        .HasColumnType("date");

                    b.Property<string>("Description")
                        .HasColumnType("longtext");

                    b.Property<int>("IdCategorie")
                        .HasColumnType("int");

                    b.Property<int>("IdCategorieNavigationIdCategorie")
                        .HasColumnType("int");

                    b.Property<int>("IdUser")
                        .HasColumnType("int");

                    b.Property<string>("ImageUrl")
                        .HasColumnType("longtext");

                    b.Property<decimal>("Prix")
                        .HasColumnType("decimal(65,30)");

                    b.Property<string>("Statut")
                        .HasColumnType("longtext");

                    b.Property<string>("Titre")
                        .IsRequired()
                        .HasColumnType("longtext");

                    b.HasKey("IdProduit");

                    b.HasIndex("IdCategorieNavigationIdCategorie");

                    b.HasIndex("IdUser");

                    b.ToTable("Produits");
                });

            modelBuilder.Entity("EcoFoodAPI.Models.Rating", b =>
                {
                    b.Property<int>("IdRating")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    b.Property<string>("Commentaire")
                        .HasColumnType("longtext");

                    b.Property<DateTime?>("DateRating")
                        .HasColumnType("datetime(6)");

                    b.Property<int>("IdFromUser")
                        .HasColumnType("int");

                    b.Property<int>("IdToUser")
                        .HasColumnType("int");

                    b.Property<int?>("Note")
                        .HasColumnType("int");

                    b.HasKey("IdRating");

                    b.HasIndex("IdFromUser");

                    b.HasIndex("IdToUser");

                    b.ToTable("Ratings");
                });

            modelBuilder.Entity("EcoFoodAPI.Models.Reservation", b =>
                {
                    b.Property<int>("IdReservation")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    b.Property<DateTime?>("DateReservation")
                        .HasColumnType("datetime(6)");

                    b.Property<int>("IdProduit")
                        .HasColumnType("int");

                    b.Property<int>("IdProduitNavigationIdProduit")
                        .HasColumnType("int");

                    b.Property<int>("IdUser")
                        .HasColumnType("int");

                    b.Property<string>("Statut")
                        .HasColumnType("longtext");

                    b.HasKey("IdReservation");

                    b.HasIndex("IdProduitNavigationIdProduit");

                    b.HasIndex("IdUser");

                    b.ToTable("Reservations");
                });

            modelBuilder.Entity("EcoFoodAPI.Models.User", b =>
                {
                    b.Property<int>("IdUser")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    b.Property<string>("Email")
                        .IsRequired()
                        .HasMaxLength(255)
                        .HasColumnType("varchar(255)");

                    b.Property<string>("MotDePasse")
                        .IsRequired()
                        .HasMaxLength(255)
                        .HasColumnType("varchar(255)");

                    b.Property<decimal?>("MoyenneRating")
                        .HasColumnType("decimal(3,2)");

                    b.Property<string>("Nom")
                        .IsRequired()
                        .HasMaxLength(50)
                        .HasColumnType("varchar(50)");

                    b.Property<string>("Prenom")
                        .IsRequired()
                        .HasMaxLength(50)
                        .HasColumnType("varchar(50)");

                    b.Property<string>("Role")
                        .ValueGeneratedOnAdd()
                        .HasMaxLength(20)
                        .HasColumnType("varchar(20)")
                        .HasDefaultValue("User");

                    b.Property<int?>("TotalRatingsDonnes")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int")
                        .HasDefaultValue(0);

                    b.Property<int?>("TotalRatingsRecus")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int")
                        .HasDefaultValue(0);

                    b.Property<string>("Ville")
                        .HasMaxLength(100)
                        .HasColumnType("varchar(100)");

                    b.HasKey("IdUser");

                    b.HasIndex("Email")
                        .IsUnique();

                    b.ToTable("Users");
                });

            modelBuilder.Entity("EcoFoodAPI.Models.Message", b =>
                {
                    b.HasOne("EcoFoodAPI.Models.Produit", "IdProduitNavigation")
                        .WithMany("Messages")
                        .HasForeignKey("IdProduitNavigationIdProduit")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.HasOne("EcoFoodAPI.Models.User", "IdReceiverNavigation")
                        .WithMany("MessageIdReceiverNavigations")
                        .HasForeignKey("IdReceiver")
                        .OnDelete(DeleteBehavior.Restrict)
                        .IsRequired();

                    b.HasOne("EcoFoodAPI.Models.User", "IdSenderNavigation")
                        .WithMany("MessageIdSenderNavigations")
                        .HasForeignKey("IdSender")
                        .OnDelete(DeleteBehavior.Restrict)
                        .IsRequired();

                    b.Navigation("IdProduitNavigation");

                    b.Navigation("IdReceiverNavigation");

                    b.Navigation("IdSenderNavigation");
                });

            modelBuilder.Entity("EcoFoodAPI.Models.Produit", b =>
                {
                    b.HasOne("EcoFoodAPI.Models.Categorie", "IdCategorieNavigation")
                        .WithMany("Produits")
                        .HasForeignKey("IdCategorieNavigationIdCategorie")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.HasOne("EcoFoodAPI.Models.User", "IdUserNavigation")
                        .WithMany("Produits")
                        .HasForeignKey("IdUser")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("IdCategorieNavigation");

                    b.Navigation("IdUserNavigation");
                });

            modelBuilder.Entity("EcoFoodAPI.Models.Rating", b =>
                {
                    b.HasOne("EcoFoodAPI.Models.User", "IdFromUserNavigation")
                        .WithMany("RatingIdFromUserNavigations")
                        .HasForeignKey("IdFromUser")
                        .OnDelete(DeleteBehavior.Restrict)
                        .IsRequired();

                    b.HasOne("EcoFoodAPI.Models.User", "IdToUserNavigation")
                        .WithMany("RatingIdToUserNavigations")
                        .HasForeignKey("IdToUser")
                        .OnDelete(DeleteBehavior.Restrict)
                        .IsRequired();

                    b.Navigation("IdFromUserNavigation");

                    b.Navigation("IdToUserNavigation");
                });

            modelBuilder.Entity("EcoFoodAPI.Models.Reservation", b =>
                {
                    b.HasOne("EcoFoodAPI.Models.Produit", "IdProduitNavigation")
                        .WithMany("Reservations")
                        .HasForeignKey("IdProduitNavigationIdProduit")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.HasOne("EcoFoodAPI.Models.User", "IdUserNavigation")
                        .WithMany("Reservations")
                        .HasForeignKey("IdUser")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("IdProduitNavigation");

                    b.Navigation("IdUserNavigation");
                });

            modelBuilder.Entity("EcoFoodAPI.Models.Categorie", b =>
                {
                    b.Navigation("Produits");
                });

            modelBuilder.Entity("EcoFoodAPI.Models.Produit", b =>
                {
                    b.Navigation("Messages");

                    b.Navigation("Reservations");
                });

            modelBuilder.Entity("EcoFoodAPI.Models.User", b =>
                {
                    b.Navigation("MessageIdReceiverNavigations");

                    b.Navigation("MessageIdSenderNavigations");

                    b.Navigation("Produits");

                    b.Navigation("RatingIdFromUserNavigations");

                    b.Navigation("RatingIdToUserNavigations");

                    b.Navigation("Reservations");
                });
#pragma warning restore 612, 618
        }
    }
}
